ASNProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path('index/', views.index, name='index'),

    path('index/index_registro_empresa/',
         views.index_registro_empresa, name='index_registro_empresa'),

    path('index/post_registro_empresa', views.post_registro_empresa,
         name='post_registro_empresa'),

    path('index/index_datos_registro', views.index_datos_registro,
         name='index_datos_registro'),

    path('index/post_registro_empresa/datos_registro/', views.index_datos_registro,
         name='datos_registro'),

    # coordinador

    path('coordinador/',
         views.coordinador, name='coordinador'),

    path('coordinador/registrar_estudiante/', views.registrar_estudiante,
         name='registrar_estudiante'),

    path('coordinador/post_registro_estudiante/', views.post_registro_estudiante,
         name='post_registro_estudiante'),

    path('coordinador/lista_estudiantes/', views.lista_estudiantes,
         name='lista_estudiantes'),

    path('coordinador/lista_empresas/', views.lista_empresas,
         name='lista_empresas'),

    path('coordinador/historico_convocatorias/', views.historico_convocatorias,
         name='historico_convocatorias'),

    path('coordinador/lista_convocatorias_empresa/', views.lista_convocatorias_empresa,
         name='lista_convocatorias_empresa'),

    path('coordinador/actualizar_semestre/', views.actualizar_semestre,
         name='actualizar_semestre'),




    # empresa

    path('empresa/',
         views.empresa, name='empresa'),

    path('empresa/registrar_convocatoria/', views.registrar_convocatoria,
         name='registrar_convocatoria'),

    path('empresa/post_registro_convocatoria/', views.post_registro_convocatoria,
         name='post_registro_convocatoria'),

    path('empresa/lista_convocatorias/', views.lista_convocatorias,
         name='lista_convocatorias'),

    path('empresa/lista_convocatorias/editar_convocatoria/', views.editar_convocatoria,
         name='editar_convocatoria'),



    # Estudiante

    path('estudiante/',
         views.estudiante, name='estudiante'),

    path('estudiante/convocatorias_abiertas/', views.convocatorias_abiertas,
         name='convocatorias_abiertas'),

    path('estudiante/actualizar_perfil/', views.actualizar_perfil,
         name='actualizar_perfil'),

    path('estudiante/post_actualizar_perfil/', views.post_actualizar_perfil,
         name='post_actualizar_perfil'),





]

usuarios/models.py
from django.db import models
from django.db.models.fields import DateTimeField
import datetime

# Create your models here.


class registro(models.Model): ##registro empresa
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    razon_social = models.CharField(max_length=60)
    ciudad = models.CharField(max_length=50)
    nombre_contacto = models.CharField(max_length=50)
    email = models.EmailField()


class crear_estudiante(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    nombre_completo = models.CharField(max_length=50)
    apellido_completo = models.CharField(max_length=50)
    email = models.EmailField()

class crear_convocatoria(models.Model):
    nombre = models.CharField(max_length=30)
    fecha_inicial = models.CharField(max_length=30)
    fecha_final = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=500)

class editar_perfil(models.Model):
    email = models.EmailField
    fortalezas = models.CharField(max_length=100)
    herramientas = models.CharField(max_length=100)

usuarios/views.py
from django.shortcuts import redirect, render
from usuarios.models import registro, crear_estudiante, crear_convocatoria, editar_perfil
from django.http import request
from django.http.response import HttpResponse
from django.http import HttpResponse

# Create your views here.


def index(request):

    return render(request, "index/index.html")


def index_registro_empresa(request):

    return render(request, "index/index_registro_empresa.html")


def index_datos_registro(request):

    return render(request, "index/index_datos_registro.html")


def post_registro_empresa(request):
    username = request.POST['username']
    password = request.POST['password']
    razon_social = request.POST['razon_social']
    ciudad = request.POST['ciudad']
    nombre_contacto = request.POST['nombre_contacto']
    email = request.POST['email']

    # Crear el objeto

    user = registro(username=username, password=password, razon_social=razon_social,
                    ciudad=ciudad, nombre_contacto=nombre_contacto, email=email)
    user.save()

    return HttpResponse("Inscripción Enviada al Servidor")


# coordinador

def coordinador(request):
    return render(request, "coordinador/coordinador.html")


def registrar_estudiante(request):
    return render(request, "coordinador/crear_estudiante/crear_estudiante.html")


def post_registro_estudiante(request):
    username = request.POST['username']
    password = request.POST['password']
    nombre_completo = request.POST['nombre_completo']
    apellido_completo = request.POST['apellido_completo']
    email = request.POST['email']

    # Crear el objeto

    registro_estudiante = crear_estudiante(username=username, password=password, nombre_completo=nombre_completo,
                                           apellido_completo=apellido_completo, email=email)
    registro_estudiante.save()

    return HttpResponse("Inscripción Enviada al Servidor")


def lista_estudiantes(request):

    # Obtiene a los estudiantes registrados
    lista = crear_estudiante.objects.all()
    # crear el contexto
    contexto = {
        'lista_registro_estudiantes': lista
    }
    return render(request, "coordinador/lista_estudiantes/lista_estudiantes.html", contexto)


def lista_empresas(request):

    # Obtiene a los estudiantes registrados
    lista = registro.objects.all()
    # crear el contexto
    contexto = {
        'lista_registro_empresas': lista
    }

    return render(request, "coordinador/lista_empresas/datos_empresa.html", contexto)


def historico_convocatorias(request):

    # Obtiene a los estudiantes registrados
    lista = crear_convocatoria.objects.all()
    # crear el contexto
    contexto = {
        'lista_historico_convocatorias': lista
    }

    return render(request, "coordinador/histo_conv/hist_conv.html", contexto)


def lista_convocatorias_empresa(request):

    # Obtiene a los estudiantes registrados
    lista = crear_convocatoria.objects.all()
    # crear el contexto
    contexto = {
        'lista_historico_convocatorias': lista
    }

    return render(request, "coordinador/lista_empresas/lista_convocatorias.html", contexto)


def actualizar_semestre(request):
    return render(request, "coordinador/actualizar_semestre/semestre.html")

    # Empresa


def empresa(request):
    return render(request, "empresa/empresa.html")


def convocatorias_abiertas(request):
    return render(request, "estudiante/convocatorias_abiertas/convocatorias_abiertas.html")


def post_registro_convocatoria(request):
    nombre = request.POST['nombre']
    fecha_inicial = request.POST['fecha_inicial']
    fecha_final = request.POST['fecha_final']
    descripcion = request.POST['descripcion']

    # Crear el objeto

    registro_convocatoria = crear_convocatoria(nombre=nombre, fecha_inicial=fecha_inicial, fecha_final=fecha_final,
                                               descripcion=descripcion)
    registro_convocatoria.save()

    return HttpResponse("Registro convocatoria Enviada al Servidor")


def lista_convocatorias(request):

    # Obtiene a los estudiantes registrados
    lista = crear_convocatoria.objects.all()
    # crear el contexto
    contexto = {
        'lista_convocatorias': lista
    }
    return render(request, "empresa/lista_conovocatorias/lista_convocatorias.html", contexto)


def editar_convocatoria(request):
    return render(request, "empresa/lista_conovocatorias/editar_convocatoria.html")

    # Estudiante


def estudiante(request):
    return render(request, "estudiante/estudiante.html")


def registrar_convocatoria(request):
    return render(request, "empresa/convocatoria/crear_convocatoria.html")


def post_registro_convocatoria(request):
    nombre = request.POST['nombre']
    fecha_inicial = request.POST['fecha_inicial']
    fecha_final = request.POST['fecha_final']
    descripcion = request.POST['descripcion']

    # Crear el objeto

    registro_convocatoria = crear_convocatoria(nombre=nombre, fecha_inicial=fecha_inicial, fecha_final=fecha_final,
                                               descripcion=descripcion)
    registro_convocatoria.save()

    return HttpResponse("Registro convocatoria Enviada al Servidor")


def lista_convocatorias(request):

    # Obtiene a los estudiantes registrados
    lista = crear_convocatoria.objects.all()
    # crear el contexto
    contexto = {
        'lista_convocatorias': lista
    }
    return render(request, "empresa/lista_conovocatorias/lista_convocatorias.html", contexto)


def actualizar_perfil(request):
    return render(request, "estudiante/editar_perfil.html")


def post_actualizar_perfil(request):
    email = request.POST['email']
    fortalezas = request.POST['fortalezas']
    herramientas = request.POST['herramientas']

    # Crear el objeto

    perfil = editar_perfil(
        email=email, fortalezas=fortalezas, herramientas=herramientas)
    perfil.save()
    return HttpResponse("Registro convocatoria Enviada al Servidor")


def actualizado(request):

    actualizado = editar_perfil.objects.last()
    contexto = {
        'perfil_actualizado': actualizado
    }

    return render(request, "estudiante/estudiante.html", contexto)

usuarios/templates/empresa/empresa.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Empresa USTA TELECO</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'app/css/w3.css' %}">
<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
<link rel="stylesheet" href="{% static 'app/css/button.css' %}">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/f6bd73bd51.js" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

<body class="background_all">

  <!-- Page Container -->
  <div class="margen_izq margen_arriba" style="max-width:1400px;">

    <!-- The Grid -->
    <div class="padding w3-row-padding">

      <!-- Left Column -->
      <div class="columna_derecha w3-third">

        <div class="background_contendores sombreado_contenedores ">
          <div class="posicion_nombre w3-display-container">
            <img src="{% static 'app/img/avatar4.gif' %}" style="width:100%" alt="Avatar">
            <div class="padding_cotenedor w3-container " style="color: black;">
              <h2>Starbucks Cofee Company</h2>
            </div>
          </div>
          <div class="padding_cotenedor w3-container">
            <p><i class="far fa-id-badge fa-fw margen_derecha_iconos tamaño_icono color_iconos"></i>Empresa</p>
            <p><i
                class="far fa-paper-plane margen_derecha_iconos tamaño_icono color_iconos"></i>starbuckscompany@gmail.com

            </p>

            <hr>

            <p class="tamaño_icono"><b><i class="fas fa-walking margen_derecha_iconos color_iconos"></i>Opciones</b>
            </p>
            <div>
               <a href="{% url 'usuarios:registrar_convocatoria' %}"> <button class="custom-btn btn-1">Crear una
                  Convocatoria </button> </a>
            <a href="{% url 'usuarios:lista_convocatorias' %}"> <button class="custom-btn btn-1">Lista
                  de
                  Convocatorias
                </button> </a>
              <a href="/index/index.html"> <button class="custom-btn btn-1">Editar Datos </button> </a>


              <a href="{% url 'usuarios:index' %}"> <button class="custom-btn btn-1">Cerrar Sesión </button> </a>

              <!-- End Left Column -->
            </div>
          </div>
        </div><br>
      </div>

      <!-- Right Column -->
      <div class="margen_derecho">

        <div class=" padding_cotenedor sombreado_contenedore_derecho background_contendores">
          <h2 class=" padding_titulo"><i
              class="fas fa-book-open margen_derecha_iconos tamaño_icono_grande color_iconos"></i>Descripción</h2>
          <div class="padding_cotenedor">
            <p>Lorem ipsum dolor sit amet. Praesentium magnam consectetur vel in deserunt aspernatur est reprehenderit
              sunt hic. Nulla tempora soluta ea et odio, unde doloremque repellendus iure, iste.
            </p>
            <hr>
          </div>

          <h2 class=" padding_titulo"><i
              class="fas fa-location-arrow margen_derecha_iconos tamaño_icono_grande color_iconos"></i>Dirección</h2>
          <div class="padding_cotenedor">
            <p>4517 Washington Ave. Manchester, Kentucky 39495</p>

            <hr>
          </div>

          <h2 class=" padding_titulo"><i
              class="fas fa-phone margen_derecha_iconos tamaño_icono_grande color_iconos"></i>Telefono</h2>
          <div class="padding_cotenedor">
            <p>(406) 555-0120</p>
            <hr>
          </div>

        </div>

      </div>

      <!-- End Right Column -->
    </div>

    <!-- End Grid -->
  </div>

  <!-- End Page Container -->
  </div>


</body>

</html>